version: '3'
services:
  indy-node:
    image: hyperledgerlabs/indy-node:stable
    ports:
      - 9701:9701
      - 9702:9702
      - 9703:9703
      - 9704:9704
    volumes:
      - ./data:/var/lib/indy
    command: start

  hospital1:
    build:
      context: ./hospital1
      dockerfile: hospital1.dockerfile
    ports:
      - 3001:3000
    volumes:
      - ./hospital1:/app
    depends_on:
      - indy-node

  hospital2:
    build:
      context: ./hospital2
      dockerfile: hospital2.dockerfile
    ports:
      - 3002:3000
    volumes:
      - ./hospital2:/app
    depends_on:
      - indy-node

  patient:
    build:
      context: ./patient
      dockerfile: patient.dockerfile
    ports:
      - 3003:3000
    volumes:
      - ./patient:/app
    depends_on:
      - indy-node
